### PR TITLE
Many new and updated icons and links

### PR DESCRIPTION
**Pull request by HoratiuMl**
12 new icons:
- AliExpress
- Audio Recorder
- Backgammon Free
- ConnectBot
- Google Messenger
- Google News and Weather
- Influence
- Plague Inc
- QR Reader
- Sketch
- Spades Free
- Twitch

5 updated icons:
- File managers (3)
- Google Phone
- Minecraft

6 updated links for:
- Google Contacts
- QuizUp
- Steam
- uTorrent
- VLC
- Wikipedia

2 new links for:
- Amaze File Manager
- ASUS Weather

### CODE REVIEW

**Comment by bil-elmoussaoui** [comment]
Hey, 
First of all, thanks for your PR. We have been working recently to improve and update all of our Circle/Square icon themes. We have moved the source code of all the icons to https://github.com/numixproject/numix-core. Can you please create your PR there instead? The icons will be generated later by me and included on a new version of the application. 
Thanks!

**Comment by HoratiuMl** [comment]
Oh, ok.

I will but unfortunately I'm not sure when, since I'm quite busy with other projects right now.

**Comment by bil-elmoussaoui** [comment]
Thanks! While doing so, please check if any of the icons that you want to push to the new repo, isn't there already :+1: 
If you think you won't have enough time for this, i can do that for you and keep your credits of course!

**Comment by HoratiuMl** [comment]
Well many of the icons that I added are from the original desktop icon pack... So how come they don't already appear in the app? I will merge the new ones in the new repo but I want to improve them a little.

**Pull request closed without merging**
